from __future__ import annotations

from enum import Enum
from math import sqrt
from statistics import NormalDist
from typing import Sequence

from .models import InventoryNode


class PolicyType(str, Enum):
    BASE_STOCK = "base_stock"
    CRITICAL_RATIO = "critical_ratio"
    ECHELON_BASE_STOCK = "echelon_base_stock"


def base_stock_target(node: InventoryNode) -> float:
    """Return a service-level base-stock target for a single node."""
    return node.reorder_point()


def critical_ratio_target(node: InventoryNode) -> float:
    """Return a newsvendor-style lead-time demand quantile target."""
    ratio = node.shortage_cost / (node.shortage_cost + node.holding_cost)
    z = NormalDist().inv_cdf(ratio)
    mean = node.lead_time_demand_mean()
    std = node.lead_time_demand_std()
    return max(0.0, mean + z * std)


def echelon_base_stock_targets(nodes: Sequence[InventoryNode]) -> dict[str, float]:
    """Return transparent echelon base-stock heuristic targets for a serial network.

    In a serial chain, demand is not summed across stages because upstream orders
    are generated by the same downstream material flow. The customer-facing
    demand moments are therefore propagated upstream while cumulative lead-time
    exposure grows for higher echelons.

    This remains a heuristic and is not an exact Clark-Scarf dynamic-programming
    solution.
    """
    node_list = list(nodes)
    if not node_list:
        return {}

    customer = node_list[-1]
    targets: dict[str, float] = {}

    for i, node in enumerate(node_list):
        cumulative_lead_time = sum(n.lead_time for n in node_list[i:])
        mean = customer.demand_mean * cumulative_lead_time
        std = customer.demand_std * sqrt(cumulative_lead_time)
        targets[node.name] = max(0.0, mean + node.service_z * std)

    return targets


def policy_targets(
    nodes: Sequence[InventoryNode], policy: PolicyType
) -> dict[str, float]:
    if policy is PolicyType.BASE_STOCK:
        return {node.name: base_stock_target(node) for node in nodes}
    if policy is PolicyType.CRITICAL_RATIO:
        return {node.name: critical_ratio_target(node) for node in nodes}
    if policy is PolicyType.ECHELON_BASE_STOCK:
        return echelon_base_stock_targets(nodes)
    raise ValueError(f"Unsupported policy: {policy}")
