from __future__ import annotations

from enum import Enum
from math import sqrt
from statistics import NormalDist
from typing import Sequence

from .models import InventoryNode


class PolicyType(str, Enum):
    BASE_STOCK = "base_stock"
    CRITICAL_RATIO = "critical_ratio"
    ECHELON_BASE_STOCK = "echelon_base_stock"
    S_S = "s_S"
    R_Q = "R_Q"


def base_stock_target(node: InventoryNode) -> float:
    """Return a service-level base-stock target for a single node."""
    return node.reorder_point()


def critical_ratio_target(node: InventoryNode) -> float:
    """Return a newsvendor-style lead-time demand quantile target."""
    ratio = node.shortage_cost / (node.shortage_cost + node.holding_cost)
    z = NormalDist().inv_cdf(ratio)
    mean = node.lead_time_demand_mean()
    std = node.lead_time_demand_std()
    return max(0.0, mean + z * std)


def economic_order_quantity(node: InventoryNode) -> float:
    """Return a period-consistent EOQ-style lot size.

    ``ordering_cost`` is interpreted as a fixed cost per replenishment order and
    ``holding_cost`` as a per-unit, per-period cost. If the fixed ordering cost or
    mean demand is zero, a one-period mean-demand lot is used as a conservative
    fallback so fixed-quantity policies remain operational.
    """
    if node.demand_mean <= 0:
        return 0.0
    if node.ordering_cost <= 0:
        return node.demand_mean
    return sqrt(2.0 * node.ordering_cost * node.demand_mean / node.holding_cost)


def s_s_parameters(node: InventoryNode) -> tuple[float, float]:
    """Return heuristic ``(s, S)`` parameters for one installation.

    The reorder threshold ``s`` is the service-level reorder point and ``S`` is
    set one EOQ-style lot above ``s``. These are transparent reference parameters,
    not the result of an exact stochastic dynamic-programming solution.
    """
    s = node.reorder_point()
    return s, s + economic_order_quantity(node)


def r_q_parameters(node: InventoryNode) -> tuple[float, float]:
    """Return heuristic ``(R, Q)`` reorder-point/fixed-quantity parameters."""
    return node.reorder_point(), economic_order_quantity(node)


def echelon_base_stock_targets(nodes: Sequence[InventoryNode]) -> dict[str, float]:
    """Return transparent echelon base-stock heuristic targets for a serial network.

    In a serial chain, demand is not summed across stages because upstream orders
    are generated by the same downstream material flow. Customer-facing demand
    moments are propagated upstream while cumulative replenishment exposure grows
    for higher echelons.

    Lead-time uncertainty uses the variance approximation
    ``E[L] Var(D) + E[D]^2 Var(L)``. Independent node lead-time variances are
    added across the cumulative path.

    This remains a heuristic and is not an exact Clark-Scarf dynamic-programming
    solution.
    """
    node_list = list(nodes)
    if not node_list:
        return {}

    customer = node_list[-1]
    targets: dict[str, float] = {}

    for i, node in enumerate(node_list):
        path = node_list[i:]
        cumulative_lead_time = sum(n.lead_time for n in path)
        cumulative_lead_time_variance = sum(n.lead_time_std**2 for n in path)

        mean = customer.demand_mean * cumulative_lead_time
        variance = (
            cumulative_lead_time * customer.demand_std**2
            + customer.demand_mean**2 * cumulative_lead_time_variance
        )
        std = variance**0.5
        targets[node.name] = max(0.0, mean + node.service_z * std)

    return targets


def policy_targets(
    nodes: Sequence[InventoryNode], policy: PolicyType
) -> dict[str, float]:
    if policy is PolicyType.BASE_STOCK:
        return {node.name: base_stock_target(node) for node in nodes}
    if policy is PolicyType.CRITICAL_RATIO:
        return {node.name: critical_ratio_target(node) for node in nodes}
    if policy is PolicyType.ECHELON_BASE_STOCK:
        return echelon_base_stock_targets(nodes)
    if policy is PolicyType.S_S:
        return {node.name: s_s_parameters(node)[1] for node in nodes}
    if policy is PolicyType.R_Q:
        return {node.name: r_q_parameters(node)[0] for node in nodes}
    raise ValueError(f"Unsupported policy: {policy}")


def replenishment_quantity(
    node: InventoryNode,
    policy: PolicyType,
    inventory_position: float,
    target: float,
) -> float:
    """Return the unconstrained replenishment quantity for a policy decision."""
    if policy in {
        PolicyType.BASE_STOCK,
        PolicyType.CRITICAL_RATIO,
        PolicyType.ECHELON_BASE_STOCK,
    }:
        return max(0.0, target - inventory_position)

    if policy is PolicyType.S_S:
        reorder_point, order_up_to = s_s_parameters(node)
        if inventory_position <= reorder_point:
            return max(0.0, order_up_to - inventory_position)
        return 0.0

    if policy is PolicyType.R_Q:
        reorder_point, quantity = r_q_parameters(node)
        if inventory_position <= reorder_point:
            return max(0.0, quantity)
        return 0.0

    raise ValueError(f"Unsupported policy: {policy}")
