from __future__ import annotations

from enum import Enum
from statistics import NormalDist
from typing import Sequence

from .models import InventoryNode


class PolicyType(str, Enum):
    BASE_STOCK = "base_stock"
    CRITICAL_RATIO = "critical_ratio"
    ECHELON_BASE_STOCK = "echelon_base_stock"


def base_stock_target(node: InventoryNode) -> float:
    """Return a service-level base-stock target for a single node."""
    return node.reorder_point()


def critical_ratio_target(node: InventoryNode) -> float:
    """Return a newsvendor-style lead-time demand quantile target."""
    ratio = node.shortage_cost / (node.shortage_cost + node.holding_cost)
    z = NormalDist().inv_cdf(ratio)
    mean = node.lead_time_demand_mean()
    std = node.lead_time_demand_std()
    return max(0.0, mean + z * std)


def echelon_base_stock_targets(nodes: Sequence[InventoryNode]) -> dict[str, float]:
    """Return transparent echelon base-stock heuristic targets for a serial network.

    In a serial chain, demand is not summed across stages because upstream orders
    are generated by the same downstream material flow. Customer-facing demand
    moments are propagated upstream while cumulative replenishment exposure grows
    for higher echelons.

    Lead-time uncertainty uses the variance approximation
    ``E[L] Var(D) + E[D]^2 Var(L)``. Independent node lead-time variances are
    added across the cumulative path.

    This remains a heuristic and is not an exact Clark-Scarf dynamic-programming
    solution.
    """
    node_list = list(nodes)
    if not node_list:
        return {}

    customer = node_list[-1]
    targets: dict[str, float] = {}

    for i, node in enumerate(node_list):
        path = node_list[i:]
        cumulative_lead_time = sum(n.lead_time for n in path)
        cumulative_lead_time_variance = sum(n.lead_time_std**2 for n in path)

        mean = customer.demand_mean * cumulative_lead_time
        variance = (
            cumulative_lead_time * customer.demand_std**2
            + customer.demand_mean**2 * cumulative_lead_time_variance
        )
        std = variance**0.5
        targets[node.name] = max(0.0, mean + node.service_z * std)

    return targets


def policy_targets(
    nodes: Sequence[InventoryNode], policy: PolicyType
) -> dict[str, float]:
    if policy is PolicyType.BASE_STOCK:
        return {node.name: base_stock_target(node) for node in nodes}
    if policy is PolicyType.CRITICAL_RATIO:
        return {node.name: critical_ratio_target(node) for node in nodes}
    if policy is PolicyType.ECHELON_BASE_STOCK:
        return echelon_base_stock_targets(nodes)
    raise ValueError(f"Unsupported policy: {policy}")
